# Generated by Django 5.2.4 on 2025-08-05 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("spins", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="spin",
            name="album_cover_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
